name: ExpenseTracker

services:
  postgres:
    image: postgres
    container_name: postgres27
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafka:
    image: bitnami/kafka
    container_name: kafka27
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  userservice:
    image: userservice
    container_name: userService27
    ports:
        - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  authservice:
    image: authservice
    container_name: authService27
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  insightservice:
    image: insightservice
    container_name: insightService27
    env_file:
      - /home/tanishq/PycharmProjects/InsightService/.env
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
  
  expenseservice:
    image: expenseservice
    container_name: expenseService27
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    
volumes:
  postgres_data:
