_format_version: "2.1"
_transform: true

services:
  - name: auth-service
    url: http://authservice:3001
    routes:
      - name: auth-routes
        paths:
          - /auth/v1
        strip_path: false
        preserve_host: false

  - name: expense-service
    url: http://expenseservice:3000
    routes:
      - name: expense-routes
        paths:
          - /expense/v1
        strip_path: false
        preserve_host: false
    plugins:
      - name: auth
        config:
          auth_service_url: http://authservice:3001/auth/v1/ping

  - name: user-service
    url: http://userservice:8080
    routes:
      - name: user-routes
        paths:
          - /user/v1
        strip_path: false
        preserve_host: false
    plugins:
      - name: auth
        config:
          auth_service_url: http://authservice:3001/auth/v1/ping

  - name: insight-service
    url: http://insightservice:5000
    routes:
      - name: insight-routes
        paths:
          - /insight/v1
        strip_path: false
        preserve_host: false
    plugins:
      - name: auth
        config:
          auth_service_url: http://authservice:3001/auth/v1/ping
