_format_version: "2.1"

services:
- name: auth-service
  url: http://localhost:3001
  routes:
  - name: sign-up
    paths:
    - /auth/v1/signup

- name: user-service
  url: http://localhost:8080
  routes:
  - name: get-user
    paths:
    - /user/v1/user