_format_version: "3.0"
_transform: true

services:
  # Auth Service
  - name: auth-service
    url: http://authservice:3001
    routes:
      - name: auth-routes
        paths:
          - /auth/v1
        strip_path: false

  # Expense Service
  - name: expense-service
    url: http://expenseservice:3000
    routes:
      - name: expense-routes
        paths:
          - /expense/v1
        strip_path: false
    plugins:
      - name: auth
        config:
          auth_service_url: http://authservice:3001/auth/v1/ping

  # User Service
  - name: user-service
    url: http://userservice:8080
    routes:
      - name: user-routes
        paths:
          - /user/v1
        strip_path: false
    plugins:
      - name: auth
        config:
          auth_service_url: http://authservice:3001/auth/v1/ping

  # Insight Service
  - name: insight-service
    url: http://insightservice:5000
    routes:
      - name: insight-routes
        paths:
          - /insight/v1
        strip_path: false
    plugins:
      - name: auth
        config:
          auth_service_url: http://authservice:3001/auth/v1/ping

plugins:
  # Global plugins
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
      headers:
        - Authorization
        - Content-Type
        - X-User-ID
      exposed_headers:
        - X-User-ID
      credentials: true
      max_age: 3600

  # Rate limiting plugin (optional but recommended)
  - name: rate-limiting
    config:
      minute: 100
      hour: 1000
      policy: local

  # Response transformer for security headers
  # - name: response-transformer
  #   config:
  #     add: 
  #       headers:
  #         - "X-Frame-Options:DENY"
  #         - "X-XSS-Protection:1; mode=block"
  #         - "X-Content-Type-Options:nosniff"